platform :ios, '11.0'
inhibit_all_warnings!
#use_frameworks!

target 'AnalyticsCollector_Example' do
  pod 'AnalyticsCollector', :path => '../'

  target 'AnalyticsCollector_Tests' do
    inherit! :search_paths

  end
end
